version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_ROOT_PASSWORD=F`)!XRSRwqAqy>9JUyB]Knx)S}CHB(nx
      - MYSQL_DATABASE=boardgame-db
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=F`)!XRSRwqAqy>9JUyB]Knx)S}CHB(nx
      - MYSQL_DATABASE=boardgame-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
